language: node_js
node_js:
  - '4.4'

script: 'curl -s https://gist.githubusercontent.com/jonrohan/88bdb6c2a7ddf95d83ffb8b21afdded6/raw/db9371d89a4719365d990c8070d158d16c22b124/travis-apm.sh | sh'

git:
  depth: 10

sudo: false

os:
  - linux
  - osx

env:
  global:
    - APM_TEST_PACKAGES=""

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
